### ISSUE TITLE
import error simpleio

### ISSUE THREAD

**Issue by chalmerlowe** [seawolf42/lessons#1]
I tried to run the code for the Thermistor project and `simpleio` was not found.
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 3, in <module>
ImportError: no module named 'simpleio'
```

`simpleio` is also found in:
* the light sensor project
* the accelerometer project

**Comment by seawolf42** [comment]
Great catch, thanks! Fixed in 8d2a084f
